[package]
name = 'bash-algo'
slug = 'algo'
version = '0.2.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Common algorithms implemented in pure Bash'

[run]
dependencies = ['https://github.com/hyperupcall/bats-all@v4.3.0', 'https://github.com/hyperupcall/bash-core@v0.6.0']
sourceDirs = ['pkg/src/public', 'pkg/src/util']
builtinDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
shift_verbose = 'on'
